# Generated by Django 5.0.7 on 2025-01-26 16:29

import app.common.helpers.custom_fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата и время заказа"
                    ),
                ),
                (
                    "total_price",
                    app.common.helpers.custom_fields.CurrencyField(
                        decimal_places=2, max_digits=7
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
            },
        ),
        migrations.CreateModel(
            name="OrderedDish",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "restaurant_name",
                    models.CharField(verbose_name="название ресторана"),
                ),
                ("dish_title", models.CharField(verbose_name="название блюда")),
                (
                    "dish_price",
                    app.common.helpers.custom_fields.CurrencyField(
                        decimal_places=2, max_digits=7
                    ),
                ),
                (
                    "dish_quantity",
                    models.PositiveIntegerField(verbose_name="количество блюд"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordered_dishes",
                        to="order.order",
                        verbose_name="заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "заказанное блюдо",
                "verbose_name_plural": "заказанные блюда",
            },
        ),
    ]
