# Generated by Django 5.0.7 on 2024-08-04 19:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата и время заказа')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='стоимость заказа')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderedDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='цена')),
                ('quantity', models.PositiveBigIntegerField(verbose_name='количество')),
            ],
            options={
                'verbose_name': 'заказанное блюдо',
                'verbose_name_plural': 'заказанные блюда',
            },
        ),
    ]
