# Generated by Django 5.0.7 on 2024-08-04 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='order.ordereddish', verbose_name='заказанные блюда'),
        ),
    ]
