[mypy]
exclude = 
    ^.*migrations.*,
    .env,
    .venv,
    env/,
    venv/,
    ENV/,
    env.bak/,
    venv.bak/
plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = "delivery_cub.settings"

[mypy-django_filters.*]
ignore_missing_imports = True