services:

  db:
    image: postgres:12.19
    restart: always
    env_file:
      - ./.env.dev
    volumes:
      - delivery_cub_db_dev:/var/lib/postgresql/data
    ports:
      - 8001:5432

volumes:
  delivery_cub_db_dev: