services:

  web:
    restart: always
    build:
      context: ./delivery_cub
      dockerfile: Dockerfile.prod
    command: gunicorn delivery_cub.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./delivery_cub/static:/home/app/web/staticfiles
    env_file:
      - ./.env.prod
    expose:
      - 8000
    depends_on:
      - db

  db:
    image: postgres:12.19
    restart: always
    env_file:
      - ./.env.prod
    volumes:
      - .dev/postgres-data:/var/lib/postgresql/data
  
  nginx:
    build: ./nginx
    volumes:
      - ./delivery_cub/static:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: