services:

  server-django:
    restart: always
    build: ./delivery_cub
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DJANGO_ADMIN_NAME=${DJANGO_ADMIN_NAME}
      - DJANGO_ADMIN_PASSWORD=${DJANGO_ADMIN_PASSWORD}
      - DJANGO_ADMIN_EMAIL=${DJANGO_ADMIN_EMAIL}
    ports:
      - 8000:8000
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:12.19
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - .dev/postgres-data:/var/lib/postgresql/data
    ports:
      - 8001:5432
