services:

  web:
    restart: always
    build: ./delivery_cub
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:12.19
    restart: always
    env_file:
      - ./.env.dev
    volumes:
      - .dev/postgres-data:/var/lib/postgresql/data
    ports:
      - 8001:5432

volumes:
  postgres_data: