services:

  db:
    image: postgres:12.19
    restart: always
    env_file:
      - ./.env.dev
    volumes:
      - .dev/postgres-data:/var/lib/postgresql/data
    ports:
      - 8001:5432

volumes:
  postgres_data: