# Generated by Django 5.0.7 on 2024-11-30 13:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(unique=True, verbose_name="наименование")),
            ],
            options={
                "verbose_name": "ресторан",
                "verbose_name_plural": "рестораны",
            },
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(verbose_name="название")),
                ("description", models.CharField(verbose_name="описание")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="цена"),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dishes",
                        to="restaurant.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "блюдо",
                "verbose_name_plural": "блюда",
            },
        ),
        migrations.AddConstraint(
            model_name="dish",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "title"), name="unique_dish_per_restaurant"
            ),
        ),
    ]
