# Generated by Django 5.0.7 on 2024-11-30 13:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rate",
                    models.IntegerField(
                        choices=[
                            (1, "Very bad"),
                            (2, "Can be better"),
                            (3, "Normal"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ],
                        default=5,
                        verbose_name="оценка",
                    ),
                ),
                ("comment", models.CharField(blank=True, verbose_name="комментарий")),
                (
                    "creation_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата и время создания"
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="restaurant.restaurant",
                        verbose_name="ресторан",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "оценка",
                "verbose_name_plural": "оценки",
            },
        ),
    ]
